version: "3.2"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_USER: "mysqluser"
      MYSQL_PASSWORD: "mysqlpass"
      MYSQL_ROOT_PASSWORD: "Mysql@123"
      MYSQL_DATABASE: "mytables"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-vol:/var/lib/mysql
    networks:
      - mysql-network

volumes:
  mysql-vol:
    driver: local

networks:
  mysql-network:
    driver: bridge