
apiVersion: v1
kind: Service
metadata:
  name: mobiles-service
spec:
  ports:
    - protocol: "TCP"
      port: 8080    # Port inside the cluster
      targetPort: 8080   # Port exposed to the outside
  selector:
    app: mobiles